name: Dinamic Analysis Security Testing

on:
  push:
    branches: [ "master" ]

jobs:
  stackhawk:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: stackhawk/hawkscan-action@v2.0.3
      with:
        apiKey: ${{ secrets.HAWK_API_KEY }}