# name: Deploy Vulnerable Application                                  # workflow name

# on:
#   push:
#     branches:
#       - master
# jobs:
#   vsast:
#     uses: ./.github/workflows/sast.yml

#   deploy-heroku:
#     needs: vsast
#     name: Deploy Heroku
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v3
#       - uses: akhileshns/heroku-deploy@v3.12.14 # This is the action
#         with:
#           heroku_api_key: ${{secrets.HEROKU_API_KEY}}
#           heroku_app_name: ${{secrets.HEROKU_APP}} #Must be unique in Heroku
#           heroku_email: "neogeoakb@gmail.com"
#           remote_branch: "master"
#           usedocker: true
