name: Static Analysis Security Testing                                  # workflow name

on:
  push:
    branches:
      - master

jobs:
    secrets:
        name: Scan Secrets Horusec
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v3
        - name: Install Horusec
          continue-on-error: true
          run: |
            curl -fsSL https://raw.githubusercontent.com/ZupIT/horusec/master/deployments/scripts/install.sh | bash -s latest
            horusec start -p="./" -e="true" -o="json" -O="./horusec.json" 
        - uses: actions/upload-artifact@v3
          with:
            name: horusec
            path: horusec.json
    linter:
        name: linter dockerfile
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v3
        - uses: hadolint/hadolint-action@v3.1.0
          with:
            dockerfile: Dockerfile
        continue-on-error: true

    npmaudit:
        name: npm audit
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v3
        - uses: actions/setup-node@v3
          with:
            node-version: '8'
        - run: npm audit --registry=https://registry.npmjs.org  --json > report_npmaudit.json
          continue-on-error: true   
        - uses: actions/upload-artifact@v3
          with:
            name: npm audit
            path: report_npmaudit.json